# Data understanding

### Telco Customer Churn - Dataset Columns & Business Meaning

| Column | Business Meaning |
| :--- | :--- |
| **customerID** | A unique administrative reference code assigned to each customer account. |
| **gender** | Indicates whether the account holder is male or female. |
| **SeniorCitizen** | Indicates whether the customer belongs to the senior citizen age group (1 for Yes, 0 for No). |
| **Partner** | Refers to whether the customer has a spouse or marital partner. |
| **Dependents** | Specifies whether the customer lives with dependents, such as children or elderly family members. |
| **tenure** | The total number of consecutive months the customer has stayed with the company. |
| **PhoneService** | Shows if the customer is subscribed to a home landline phone service. |
| **MultipleLines** | Specifies whether the customer has additional phone lines connected under their account. |
| **InternetService** | The type of home broadband internet connection provided (DSL, Fiber Optic, or No Internet). |
| **OnlineSecurity** | Indicates if the customer has an add-on service for online threat and malware protection. |
| **OnlineBackup** | Indicates if the customer is subscribed to a cloud storage service for data backup. |
| **DeviceProtection** | Specifies whether the customer has insurance covering hardware failures and damage. |
| **TechSupport** | Shows if the customer subscribes to dedicated, priority technical assistance services. |
| **StreamingTV** | Indicates whether the customer uses the internet connection to stream live television channels. |
| **StreamingMovies** | Shows if the customer utilizes internet bandwidth to stream movies and on-demand video. |
| **Contract** | The duration and structure of the customer agreement (Month-to-month, One-year, or Two-year). |
| **PaperlessBilling** | Indicates if the customer receives digital statements instead of printed paper bills. |
| **PaymentMethod** | The primary payment channel used by the customer (Electronic check, Mailed check, Bank transfer, Credit card). |
| **MonthlyCharges** | The recurring amount billed to the customer each month for all active services. |
| **TotalCharges** | The cumulative amount billed to the customer over the entire duration of their relationship. |
| **Churn** | Indicates whether the customer canceled their subscription and left the company in the past month (Yes/No). |

# Data Exploration

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
df.columns=df.columns.str.strip()
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [4]:
df.drop('customerID',axis=1,inplace=True)

### Check Data Types

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   str
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   str
 3   Dependents        7043 non-null   str
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
 14  Contract          7043 non-null   str
 15  PaperlessBilling  7043 non-null   str
 16  PaymentMethod     7043 non-null   str
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   str
 19  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(17)
memory usage: 1.7 MB

In [6]:
df.head(2)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No

### Check Summary Statistics for Numerical columns

In [7]:
df.describe().round(2)

       SeniorCitizen   tenure  MonthlyCharges
count        7043.00  7043.00         7043.00
mean            0.16    32.37           64.76
std             0.37    24.56           30.09
min             0.00     0.00           18.25
25%             0.00     9.00           35.50
50%             0.00    29.00           70.35
75%             0.00    55.00           89.85
max             1.00    72.00          118.75

### Check Summary Statistics for Categorical columns

In [8]:
df.describe(include= ['object'])

C:\Users\HP\AppData\Local\Temp\ipykernel_18720\2270142546.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include= ['object'])

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

### Check Duplicates

In [9]:
df.duplicated().sum()

np.int64(22)

### Check missing values

In [10]:
df.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# Data Cleaning

### In depth check for numerical columns

In [11]:
num_cols = df.select_dtypes(include= 'number').columns
num_cols

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges'], dtype='str')

In [12]:
for col in num_cols:

    px.histogram(data_frame= df, x= col, title= col).show()
    px.box(data_frame= df, x= col, title= col).show()

### In depth check for categorical columns

In [13]:
cat_cols = df.select_dtypes(include= 'object').columns.drop('TotalCharges')
cat_cols

C:\Users\HP\AppData\Local\Temp\ipykernel_18720\3915293176.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include= 'object').columns.drop('TotalCharges')

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Churn'],
      dtype='str')

In [14]:
for col in cat_cols:

    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 100)

gender
2
<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str
----------------------------------------------------------------------------------------------------
Partner
2
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
----------------------------------------------------------------------------------------------------
Dependents
2
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------------------------------------------------------------------------------
PhoneService
2
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------------------------------------------------------------------------------
MultipleLines
3
<ArrowStringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
InternetService
3
<ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
OnlineSecurity
3
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
OnlineBackup
3
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
DeviceProtection
3
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
TechSupport
3
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
StreamingTV
3
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
StreamingMovies
3
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
Contract
3
<ArrowStringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
PaperlessBilling
2
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
----------------------------------------------------------------------------------------------------
PaymentMethod
4
<ArrowStringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
----------------------------------------------------------------------------------------------------
Churn
2
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------------------------------------------------------------------------------

In [15]:
def clean_total_charges(x):
    if type(x) == float or type(x) == int:
        return x
    elif str(x).strip() == '':
        return 0.0
    else:
        return x

df['TotalCharges'] = df['TotalCharges'].apply(clean_total_charges).astype('float')
df['TotalCharges']

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   str
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   str
 3   Dependents        7043 non-null   str
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
 14  Contract          7043 non-null   str
 15  PaperlessBilling  7043 non-null   str
 16  PaymentMethod     7043 non-null   str
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   float64
 19  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(16)
memory usage: 1.7 MB

In [17]:
services_cols = [
    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 
    'TechSupport', 'StreamingTV', 'StreamingMovies', 'MultipleLines'
]

def standardize_no(x):
    if x in ['No internet service', 'No phone service']:
        return 'No'
    return x


for col in services_cols:
    df[col] = df[col].apply(standardize_no)


for col in services_cols:
    print(f"{col}: {df[col].unique()}")

OnlineSecurity: <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
OnlineBackup: <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
DeviceProtection: <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
TechSupport: <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
StreamingTV: <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
StreamingMovies: <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
MultipleLines: <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

In [18]:
df.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [19]:
print("Shape after cleaning:", df.shape)
print("\nData Types Summary:")
print(df.dtypes.value_counts())

Shape after cleaning: (7043, 20)

Data Types Summary:
str        16
int64       2
float64     2
Name: count, dtype: int64

In [20]:
num_cols1 = df.select_dtypes(include= 'number').columns
num_cols1

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')

In [21]:
for col in num_cols1:

    px.histogram(data_frame= df, x= col, title= col).show()
    px.box(data_frame= df, x= col, title= col).show()

# Feature engineering

In [22]:
services = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 
            'TechSupport', 'StreamingTV', 'StreamingMovies']

df['Total_Services'] = df[services].apply(lambda x: (x == 'Yes').sum(), axis=1)

df['Is_Auto_Payment'] = df['PaymentMethod'].apply(
    lambda x: 1 if 'automatic' in str(x).lower() else 0)

print("New shape:", df.shape)
df[['Total_Services', 'Is_Auto_Payment']].head()

New shape: (7043, 22)

   Total_Services  Is_Auto_Payment
0               1                0
1               2                0
2               2                0
3               3                1
4               0                0

In [23]:
df.head(2)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Total_Services,Is_Auto_Payment
0,Female,0,Yes,No,1,No,No,DSL,No,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,No,One year,No,Mailed check,56.95,1889.50,No,2,0

# Save cleaned data

In [24]:
df.to_csv('cleaned_telco_data.csv', index=False)

# Data analysis

### 1. What is the overall Churn Rate in the dataset?
**Goal:** Understand the class distribution (Target Variable) to check for class imbalance.

In [25]:
fig1 = px.pie(
    df, 
    names='Churn', 
    title='Overall Customer Churn Rate', 
    hole=0.4,
    color_discrete_sequence=['#2ecc71', '#e74c3c']
)

fig1.update_traces(textposition='inside', textinfo='percent+label')
fig1.show()

### 2. How does customer tenure affect Churn?
**Goal:** Analyze if newer customers are more likely to churn compared to long-term customers.

In [26]:
fig2 = px.box(
    df, 
    x='Churn', 
    y='tenure', 
    color='Churn',
    title='Tenure Distribution by Churn Status',
    labels={'tenure': 'Tenure (Months)', 'Churn': 'Churn Status'},
    color_discrete_map={'No': '#3498db', 'Yes': '#e67e22'}
)

fig2.show()

### 3. How do Contract Types and Payment Methods relate to Churn?
**Goal:** Identify which contract terms and payment options are associated with higher customer attrition.

In [27]:
fig3_a = px.histogram(
    df, 
    x='Contract', 
    color='Churn', 
    barmode='group',
    title='Customer Count by Contract Type & Churn',
    color_discrete_map={'No': '#3498db', 'Yes': '#e67e22'},
    text_auto=True
)
fig3_a.show()

fig3_b = px.histogram(
    df, 
    x='PaymentMethod', 
    color='Churn', 
    barmode='group',
    title='Customer Count by Payment Method & Churn',
    color_discrete_map={'No': '#3498db', 'Yes': '#e67e22'},
    text_auto=True
)
fig3_b.show()

### 4. How does the total number of services subscribed affect Churn?
**Goal:** Evaluate if customers with more active services (engineered feature) are less likely to churn.

In [28]:
services_churn = df.groupby('Total_Services')['Churn'].apply(lambda x: (x == 'Yes').mean() * 100).reset_index()
services_churn.columns = ['Total_Services', 'Churn_Rate']


fig4 = px.line(
    services_churn, 
    x='Total_Services', 
    y='Churn_Rate', 
    markers=True,
    title='Churn Rate Trend by Total Services Subscribed',
    labels={'Total_Services': 'Number of Active Services', 'Churn_Rate': 'Churn Rate (%)'},
    text=services_churn['Churn_Rate'].round(1).astype(str) + '%'
)

fig4.update_traces(line_color='#e67e22', line_width=3, marker_size=10, textposition='top center')
fig4.update_layout(xaxis=dict(tickmode='linear', tick0=0, dtick=1))
fig4.show()

### 5. What is the impact of payment automation on Churn?
**Goal:** Evaluate whether customers using automatic payment methods have higher retention compared to manual payment methods.

In [29]:
fig5 = px.histogram(
    df, 
    x='Is_Auto_Payment', 
    color='Churn', 
    barnorm='percent',
    title='Churn Rate: Automatic vs. Manual Payment Methods',
    labels={'Is_Auto_Payment': 'Payment Type', 'count': 'Percentage (%)'},
    color_discrete_map={'No': '#3498db', 'Yes': '#e67e22'},
    text_auto='.1f'
)

fig5.update_layout(
    xaxis=dict(
        tickmode='array',
        tickvals=[0, 1],
        ticktext=['Manual Payment', 'Automatic Payment']
    )
)

fig5.show()

### 6. Which Internet Service type suffers from the highest Churn?
**Goal:** Determine if specific internet technologies (e.g., Fiber Optic vs. DSL) are linked to higher customer dissatisfaction and churn.

In [30]:
# رسم نسبة الـ Churn حسب نوع خدمة الإنترنت
fig6 = px.histogram(
    df, 
    x='InternetService', 
    color='Churn', 
    barnorm='percent',
    title='Churn Rate by Internet Service Type',
    labels={'InternetService': 'Internet Service Type', 'count': 'Percentage (%)'},
    color_discrete_map={'No': '#3498db', 'Yes': '#e67e22'},
    text_auto='.1f'
)

fig6.show()

### 7. Do Senior Citizens or Single Customers Churn More?
**Goal:** Examine if demographic segments (Senior Citizens & Partner status) have higher attrition rates.

In [31]:

fig7 = px.histogram(
    df, 
    x='SeniorCitizen', 
    color='Churn', 
    barnorm='percent',
    title='Churn Rate by Senior Citizen Status',
    labels={'SeniorCitizen': 'Senior Citizen Status', 'count': 'Percentage (%)'},
    color_discrete_map={'No': '#3498db', 'Yes': '#e67e22'},
    text_auto='.1f'
)

fig7.update_layout(
    xaxis=dict(
        tickmode='array',
        tickvals=[0, 1],
        ticktext=['Non-Senior', 'Senior Citizen']
    )
)

fig7.show()

### Summary of EDA Findings & Final Key Takeaways
**Goal:** Synthesize core insights from the Exploratory Data Analysis to justify feature selection and guide the machine learning pipeline.

#### **Key Analytical Insights:**

1. **Tenure Impact:** High attrition occurs mainly in the first 12 months (**0-1 Year** segment), after which retention increases significantly.
2. **Contract & Payment Risk:** **Month-to-month** contracts and **Electronic Check** payments are the primary drivers of churn.
3. **Product Engagement:** Customers subscribing to more services (**Total_Services > 3**) show drastically lower churn rates, proving the engineered feature's predictive value.
4. **Service Quality Issues:** **Fiber Optic** users experience a **41.9%** churn rate, signaling potential pricing or service quality issues compared to DSL.
5. **Demographic Risk:** **Senior Citizens** churn at almost double the rate (**41.7%**) of non-seniors (**23.6%**), highlighting a vulnerable customer segment.

# Data Preprocessing for ML

### Check correlation to prevent data leakge

In [32]:
df_encoded = pd.get_dummies(df.drop(columns=['customerID', 'tenure_group'], errors='ignore'), drop_first=True)

churn_corr = df_encoded.corr()['Churn_Yes'].abs().sort_values(ascending=False)

print("Top 10 Features correlated with Churn:")
print(churn_corr.iloc[1:11])

Top 10 Features correlated with Churn:
tenure                            0.352229
InternetService_Fiber optic       0.308020
Contract_Two year                 0.302253
PaymentMethod_Electronic check    0.301919
InternetService_No                0.227890
Is_Auto_Payment                   0.209902
TotalCharges                      0.198324
MonthlyCharges                    0.193356
PaperlessBilling_Yes              0.191825
Contract_One year                 0.177820
Name: Churn_Yes, dtype: float64

### Split Data into Input & Output Features

In [33]:
x = df.drop('Churn', axis= 1)
y = df['Churn']

### Check imbalance percentage

In [34]:
y.value_counts(normalize=True)*100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

### Remapping the target variable to binary format for modeling

In [35]:
y = df['Churn'].map({'No': 0, 'Yes': 1})
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

### Numerical Pipeline

- Numerical Pipeline 1

In [36]:
x.select_dtypes(include= 'number').columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'Total_Services', 'Is_Auto_Payment'],
      dtype='str')

In [37]:
scaling_cols = ['tenure', 'MonthlyCharges', 'TotalCharges', 'Total_Services']
scaling_cols

['tenure', 'MonthlyCharges', 'TotalCharges', 'Total_Services']

In [38]:
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler


rc = StandardScaler()
scaling_pipeline_1 = Pipeline(steps= [('Scaling', rc)])
scaling_pipeline_1

Pipeline(steps=[('Scaling', StandardScaler())])

### Categorical pipeline

- categorical pipeline 1

In [39]:
ohe_cols = x.select_dtypes(include= 'object').columns.drop('Contract')
ohe_cols

C:\Users\HP\AppData\Local\Temp\ipykernel_18720\3051444319.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  ohe_cols = x.select_dtypes(include= 'object').columns.drop('Contract')

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling',
       'PaymentMethod'],
      dtype='str')

In [40]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop= 'first', sparse_output= False)

ohe_pipeline = Pipeline(steps= [('OHE', ohe)])
ohe_pipeline

Pipeline(steps=[('OHE', OneHotEncoder(drop='first', sparse_output=False))])

- categorical pipeline 2

In [41]:
ord_cols = ['Contract']
ord_cols

['Contract']

In [42]:
from sklearn.preprocessing import OrdinalEncoder

ord = OrdinalEncoder(categories= [['Month-to-month', 'One year', 'Two year']])

ord_pipeline = Pipeline(steps= [ ('Ordinal Encoder', ord) ])
ord_pipeline

Pipeline(steps=[('Ordinal Encoder',
                 OrdinalEncoder(categories=[['Month-to-month', 'One year',
                                             'Two year']]))])

In [43]:
x['Contract'].unique()

<ArrowStringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

### Assign each column to its corresponding Pipeline

In [44]:
from sklearn.compose import ColumnTransformer

preprocessing = ColumnTransformer(
    transformers=[
        ('Num Pipeline', scaling_pipeline_1, scaling_cols),
        ('OHE Pipeline', ohe_pipeline, ohe_cols),
        ('Ordinal Pipeline', ord_pipeline, ord_cols)
    ],
    remainder='passthrough'  
)

preprocessing

ColumnTransformer(remainder='passthrough',
                  transformers=[('Num Pipeline',
                                 Pipeline(steps=[('Scaling',
                                                  StandardScaler())]),
                                 ['tenure', 'MonthlyCharges', 'TotalCharges',
                                  'Total_Services']),
                                ('OHE Pipeline',
                                 Pipeline(steps=[('OHE',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False))]),
                                 Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling',
       'PaymentMethod'],
      dtype='str')),
                                ('Ordinal Pipeline',
                                 Pipeline(steps=[('Ordinal Encoder',
                                                  OrdinalEncoder(categories=[['Month-to-month',
                                                                              'One '
                                                                              'year',
                                                                              'Two '
                                                                              'year']]))]),
                                 ['Contract'])])

### Select Best model

In [77]:
scale_pos_weight = (y == 0).sum() / (y == 1).sum()
scale_pos_weight

np.float64(2.7683253076511503)

In [78]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_validate, StratifiedKFold
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier


models = [
    ('Logistic Regression', LogisticRegression(random_state=42, class_weight='balanced')),
    ('Gaussian NB', GaussianNB()),
    ('SVC', SVC(random_state= 42)),
    ('KNN', KNeighborsClassifier()),
    ('Decision Tree', DecisionTreeClassifier(random_state=42, class_weight='balanced')),
    ('Random Forest', RandomForestClassifier(random_state=42, class_weight='balanced')),
    ('XGBoost', XGBClassifier(random_state=42, scale_pos_weight=scale_pos_weight))
]

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)



for name, model in models:
    model_pipeline = Pipeline(steps=[
        ('Preprocessing', preprocessing),
        ('Model', model)
    ])
    
    cv_result = cross_validate(
        estimator=model_pipeline,
        X=x,
        y=y,
        scoring=['precision', 'recall', 'f1', 'accuracy'],
        cv=skf,
        return_train_score=True,
        n_jobs=-1
    )
    
    print(f"=== {name} ===")
    print(f"Train Recall:    {cv_result['train_recall'].mean() * 100:.2f}%")
    print(f"Test Recall:     {cv_result['test_recall'].mean() * 100:.2f}%")
    print(f"Train Precision: {cv_result['train_precision'].mean() * 100:.2f}%")
    print(f"Test Precision:  {cv_result['test_precision'].mean() * 100:.2f}%")
    print(f"Test F1-Score:   {cv_result['test_f1'].mean() * 100:.2f}%")
    print(f"Test Accuracy:   {cv_result['test_accuracy'].mean() * 100:.2f}%")
    print('-' * 40)

=== Logistic Regression ===
Train Recall:    80.85%
Test Recall:     80.26%
Train Precision: 51.82%
Test Precision:  51.35%
Test F1-Score:   62.63%
Test Accuracy:   74.58%
----------------------------------------
=== Gaussian NB ===
Train Recall:    74.42%
Test Recall:     74.26%
Train Precision: 53.02%
Test Precision:  53.07%
Test F1-Score:   61.88%
Test Accuracy:   75.72%
----------------------------------------
=== SVC ===
Train Recall:    51.56%
Test Recall:     48.10%
Train Precision: 70.82%
Test Precision:  67.29%
Test F1-Score:   56.05%
Test Accuracy:   80.04%
----------------------------------------
=== KNN ===
Train Recall:    64.14%
Test Recall:     51.79%
Train Precision: 72.12%
Test Precision:  55.72%
Test F1-Score:   53.68%
Test Accuracy:   76.29%
----------------------------------------
=== Decision Tree ===
Train Recall:    99.96%
Test Recall:     50.13%
Train Precision: 99.15%
Test Precision:  49.79%
Test F1-Score:   49.94%
Test Accuracy:   73.35%
----------------------------------------
=== Random Forest ===
Train Recall:    99.87%
Test Recall:     47.88%
Train Precision: 99.32%
Test Precision:  63.05%
Test F1-Score:   54.39%
Test Accuracy:   78.74%
----------------------------------------
=== XGBoost ===
Train Recall:    99.32%
Test Recall:     66.51%
Train Precision: 79.20%
Test Precision:  54.03%
Test F1-Score:   59.62%
Test Accuracy:   76.09%
----------------------------------------

### Threshold

In [64]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import precision_recall_curve


model_pipeline = Pipeline(steps=[
    ('Preprocessing', preprocessing),
    ('Model', LogisticRegression(random_state=42, class_weight='balanced', max_iter=1000))
])

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

y_proba = cross_val_predict(
    estimator=model_pipeline,
    X=x,
    y=y,
    cv=skf,
    method='predict_proba',
    n_jobs=-1
)[:, 1]

In [65]:
y_proba

array([0.84139582, 0.11094489, 0.52892931, ..., 0.64461259, 0.85214092,
       0.12192672], shape=(7043,))

In [66]:
precision, recall, thresholds = precision_recall_curve(y, y_proba)

pr_df = pd.DataFrame({
    'Precision': precision[:-1],
    'Recall': recall[:-1],
    'Threshold': thresholds
})
pr_df

      Precision    Recall  Threshold
0      0.265370  1.000000   0.003202
1      0.265408  1.000000   0.003498
2      0.265445  1.000000   0.003576
3      0.265483  1.000000   0.003724
4      0.265521  1.000000   0.003837
...         ...       ...        ...
7027   1.000000  0.002675   0.936796
7028   1.000000  0.002140   0.941149
7029   1.000000  0.001605   0.941197
7030   1.000000  0.001070   0.941377
7031   1.000000  0.000535   0.942669

[7032 rows x 3 columns]

In [67]:
pr_df_filtered = pr_df[pr_df['Precision'] >= 0.60]

pr_df_sorted = pr_df_filtered.sort_values(by=['Recall', 'Precision'], ascending=[False, False])

optimum_threshold = pr_df_sorted.iloc[0]['Threshold']

print(f"Optimum Threshold: {optimum_threshold:.4f}")
print(f"Associated Recall:  {pr_df_sorted.iloc[0]['Recall'] * 100:.2f}%")
print(f"Associated Precision: {pr_df_sorted.iloc[0]['Precision'] * 100:.2f}%")

Optimum Threshold: 0.6623
Associated Recall:  64.90%
Associated Precision: 60.08%

##### Not good idea to use this threshold for production, but it can be used for analysis and understanding the trade-offs between precision and recall.

### Hyperparameter tunning by GridSearch

In [79]:
from sklearn.model_selection import GridSearchCV

grid_params = [
    # Logistic Regression Tuning
    {
        'model': [LogisticRegression(random_state=42, class_weight='balanced', max_iter=1000)],
        'params': {
            'Model__C': [0.01, 0.1, 1, 10],
            'Model__solver': ['lbfgs', 'liblinear']
        }
    },
    # Random Forest Tuning
    {
        'model': [RandomForestClassifier(random_state=42, class_weight='balanced')],
        'params': {
            'Model__n_estimators': [100, 200],
            'Model__max_depth': [3, 4, 5, 6],
            'Model__min_samples_leaf': [2, 4, 8]
        }
    },
    # XGBoost Tuning
    {
        'model': [XGBClassifier(random_state=42, scale_pos_weight=scale_pos_weight)],
        'params': {
            'Model__n_estimators': [100, 200],
            'Model__max_depth': [2, 3, 4],
            'Model__learning_rate': [0.01, 0.05, 0.1],
            'Model__subsample': [0.7, 0.8]
        }
    }
]

best_models = {}

for grid in grid_params:
    model_name = grid['model'][0].__class__.__name__
    
    pipeline = Pipeline(steps=[
        ('Preprocessing', preprocessing),
        ('Model', grid['model'][0])
    ])
    
    grid_search = GridSearchCV(
        estimator=pipeline,
        param_grid=grid['params'],
        cv=skf,
        scoring='f1',
        return_train_score=True,
        n_jobs=-1
    )
    
    grid_search.fit(x, y)
    
    best_models[model_name] = grid_search
    
    print(f"=== {model_name} ===")
    print(f"Best Parameters: {grid_search.best_params_}")
    print(f"Best Test F1-Score: {grid_search.best_score_ * 100:.2f}%")
    print('-' * 50)

=== LogisticRegression ===
Best Parameters: {'Model__C': 1, 'Model__solver': 'liblinear'}
Best Test F1-Score: 62.68%
--------------------------------------------------
=== RandomForestClassifier ===
Best Parameters: {'Model__max_depth': 6, 'Model__min_samples_leaf': 2, 'Model__n_estimators': 100}
Best Test F1-Score: 63.49%
--------------------------------------------------
=== XGBClassifier ===
Best Parameters: {'Model__learning_rate': 0.01, 'Model__max_depth': 4, 'Model__n_estimators': 200, 'Model__subsample': 0.7}
Best Test F1-Score: 63.25%
--------------------------------------------------

In [80]:
tuned_best_models = [
    ('Random Forest (Tuned)', best_models['RandomForestClassifier'].best_estimator_),
    ('XGBoost (Tuned)', best_models['XGBClassifier'].best_estimator_),
    ('Logistic Regression (Tuned)', best_models['LogisticRegression'].best_estimator_)
]

for name, model_pipe in tuned_best_models:
    cv_final = cross_validate(
        estimator=model_pipe,
        X=x,
        y=y,
        scoring=['precision', 'recall', 'f1', 'accuracy'],
        cv=skf,
        return_train_score=True,
        n_jobs=-1
    )
    
    print(f"=== {name} ===")
    print(f"Train Recall:    {cv_final['train_recall'].mean() * 100:.2f}% | Test Recall:    {cv_final['test_recall'].mean() * 100:.2f}%")
    print(f"Train Precision: {cv_final['train_precision'].mean() * 100:.2f}% | Test Precision: {cv_final['test_precision'].mean() * 100:.2f}%")
    print(f"Test F1-Score:   {cv_final['test_f1'].mean() * 100:.2f}%")
    print(f"Test Accuracy:   {cv_final['test_accuracy'].mean() * 100:.2f}%")
    print('-' * 60)

=== Random Forest (Tuned) ===
Train Recall:    82.54% | Test Recall:    79.51%
Train Precision: 54.76% | Test Precision: 52.85%
Test F1-Score:   63.49%
Test Accuracy:   75.72%
------------------------------------------------------------
=== XGBoost (Tuned) ===
Train Recall:    82.92% | Test Recall:    80.85%
Train Precision: 53.40% | Test Precision: 51.95%
Test F1-Score:   63.25%
Test Accuracy:   75.07%
------------------------------------------------------------
=== Logistic Regression (Tuned) ===
Train Recall:    80.82% | Test Recall:    80.36%
Train Precision: 51.79% | Test Precision: 51.38%
Test F1-Score:   62.68%
Test Accuracy:   74.61%
------------------------------------------------------------

### Select Best model

In [54]:
final_pipeline = best_models['XGBClassifier'].best_estimator_

final_pipeline.fit(x, y)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Scaling',
                                                                   StandardScaler())]),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges',
                                                   'Total_Services']),
                                                 ('OHE Pipeline',
                                                  Pipeline(steps=[('OHE',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse_output=False))]),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneServ...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.01,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=4, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=200, n_jobs=None,
                               num_parallel_tree=None, ...))])

### Save

In [55]:
import joblib

joblib.dump(final_pipeline, 'churn_xgb_pipeline.pkl')

['churn_xgb_pipeline.pkl']

### Testing it

In [56]:
rf_model = joblib.load('churn_xgb_pipeline.pkl')
rf_model

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Scaling',
                                                                   StandardScaler())]),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges',
                                                   'Total_Services']),
                                                 ('OHE Pipeline',
                                                  Pipeline(steps=[('OHE',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse_output=False))]),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneServ...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.01,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=4, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=200, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [57]:
x.head(1)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Total_Services,Is_Auto_Payment
0,Female,0,Yes,No,1,No,No,DSL,No,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,1,0

In [58]:
rf_model.predict(x.head(1))[0]

np.int64(1)